# Form implementation generated from reading ui file 'C:\Users\Facundo\OneDrive\Escritorio\Aprendiendopython\Proyecto_Final_python\GUI\Diseño.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt, QModelIndex
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from metodos_GUI import MisMetodos
from bd_conexion import GestionInventario



class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(879, 642)
        Dialog.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 901, 651))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setGeometry(QtCore.QRect(100, 170, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setGeometry(QtCore.QRect(100, 300, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setGeometry(QtCore.QRect(110, 370, 91, 31))
        self.label_5.setObjectName("label_5")
        self.txt_nom_prod = QtWidgets.QLineEdit(parent=self.tab)
        self.txt_nom_prod.setGeometry(QtCore.QRect(210, 180, 151, 22))
        self.txt_nom_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nom_prod.setObjectName("txt_nom_prod")
        self.txt_cat_prod = QtWidgets.QLineEdit(parent=self.tab)
        self.txt_cat_prod.setGeometry(QtCore.QRect(210, 300, 151, 22))
        self.txt_cat_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cat_prod.setObjectName("txt_cat_prod")
        self.txt_stock_prod = QtWidgets.QLineEdit(parent=self.tab)
        self.txt_stock_prod.setGeometry(QtCore.QRect(210, 370, 151, 22))
        self.txt_stock_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_stock_prod.setObjectName("txt_stock_prod")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(590, 150, 111, 31))
        self.label_3.setObjectName("label_3")
        self.des_prod = QtWidgets.QPlainTextEdit(parent=self.tab)
        self.des_prod.setGeometry(QtCore.QRect(540, 190, 221, 161))
        self.des_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.des_prod.setObjectName("des_prod")
        self.btn_agre = QtWidgets.QPushButton(parent=self.tab)
        self.btn_agre.setGeometry(QtCore.QRect(580, 500, 121, 51))
        self.btn_agre.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_agre.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_agre.setObjectName("btn_agre")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(250, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 40, 111, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(
            "C:\\Users\\Facundo\\OneDrive\\Escritorio\\Aprendiendopython\\Proyecto_Final_python\\GUI\\../Img/agregar-producto.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.lbl_msj_error = QtWidgets.QLabel(parent=self.tab)
        self.lbl_msj_error.setGeometry(QtCore.QRect(20, 440, 451, 51))
        self.lbl_msj_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_msj_error.setObjectName("lbl_msj_error")
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setGeometry(QtCore.QRect(100, 230, 91, 31))
        self.label_8.setObjectName("label_8")
        self.txt_precio_prod = QtWidgets.QLineEdit(parent=self.tab)
        self.txt_precio_prod.setGeometry(QtCore.QRect(210, 240, 151, 22))
        self.txt_precio_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_precio_prod.setObjectName("txt_precio_prod")
        self.comboBox_prod = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox_prod.setGeometry(QtCore.QRect(628, 20, 211, 22))
        self.comboBox_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_prod.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.comboBox_prod.setObjectName("comboBox_prod")
        self.comboBox_prod.addItem("")
        self.comboBox_prod.addItem("")
        self.frame_prod1 = QtWidgets.QFrame(parent=self.tab)
        self.frame_prod1.setGeometry(QtCore.QRect(0, 40, 891, 601))
        self.frame_prod1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.frame_prod1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_prod1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_prod1.setObjectName("frame_prod1")
        self.tableView_prod = QtWidgets.QTableView(parent=self.frame_prod1)
        self.tableView_prod.setGeometry(QtCore.QRect(70, 60, 541, 401))
        self.tableView_prod.setObjectName("tableView_prod")
        self.btn_cahnge_prod3 = QtWidgets.QPushButton(parent=self.frame_prod1)
        self.btn_cahnge_prod3.setGeometry(QtCore.QRect(660, 460, 141, 41))
        self.btn_cahnge_prod3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cahnge_prod3.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_cahnge_prod3.setObjectName("btn_cahnge_prod3")
        self.btn_refresh_prod_2 = QtWidgets.QPushButton(parent=self.frame_prod1)
        self.btn_refresh_prod_2.setGeometry(QtCore.QRect(630, 80, 81, 21))
        self.btn_refresh_prod_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh_prod_2.setStyleSheet("background-color: rgb(255, 212, 126);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Facundo\\OneDrive\\Escritorio\\Aprendiendopython\\Proyecto_Final_python\\GUI\\../Img/actualizar.png"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_refresh_prod_2.setIcon(icon)
        self.btn_refresh_prod_2.setObjectName("btn_refresh_prod_2")
        self.txt_serch_prod_3 = QtWidgets.QLineEdit(parent=self.frame_prod1)
        self.txt_serch_prod_3.setGeometry(QtCore.QRect(120, 30, 161, 22))
        self.txt_serch_prod_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_serch_prod_3.setObjectName("txt_serch_prod_3")
        self.btn_serch_nom_prod = QtWidgets.QPushButton(parent=self.frame_prod1)
        self.btn_serch_nom_prod.setGeometry(QtCore.QRect(290, 30, 21, 21))
        self.btn_serch_nom_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_serch_nom_prod.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_serch_nom_prod.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Facundo\\OneDrive\\Escritorio\\Aprendiendopython\\Proyecto_Final_python\\GUI\\../Img/lupa.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_serch_nom_prod.setIcon(icon1)
        self.btn_serch_nom_prod.setObjectName("btn_serch_nom_prod")
        self.label_39 = QtWidgets.QLabel(parent=self.frame_prod1)
        self.label_39.setGeometry(QtCore.QRect(60, 30, 51, 20))
        self.label_39.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_39.setObjectName("label_39")
        self.lbl_msj_error_3 = QtWidgets.QLabel(parent=self.frame_prod1)
        self.lbl_msj_error_3.setGeometry(QtCore.QRect(60, 490, 451, 51))
        self.lbl_msj_error_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_msj_error_3.setObjectName("lbl_msj_error_3")
        self.btn_generate_informe = QtWidgets.QPushButton(parent=self.tab)
        self.btn_generate_informe.setGeometry(QtCore.QRect(70, 530, 151, 31))
        self.btn_generate_informe.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_generate_informe.setObjectName("btn_generate_informe")
        self.frame_prod2 = QtWidgets.QFrame(parent=self.tab)
        self.frame_prod2.setGeometry(QtCore.QRect(0, 0, 621, 51))
        self.frame_prod2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_prod2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_prod2.setObjectName("frame_prod2")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_prod2)
        self.label_19.setGeometry(QtCore.QRect(220, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font: 24pt \"Segoe UI\";")
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(210, 20, 301, 31))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(60, 160, 81, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 240, 91, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 350, 151, 41))
        self.label_11.setObjectName("label_11")
        self.pl_txt_termino_pago = QtWidgets.QPlainTextEdit(parent=self.tab_2)
        self.pl_txt_termino_pago.setGeometry(QtCore.QRect(200, 370, 321, 121))
        self.pl_txt_termino_pago.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pl_txt_termino_pago.setObjectName("pl_txt_termino_pago")
        self.txt_provedor_contacto = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txt_provedor_contacto.setGeometry(QtCore.QRect(170, 250, 171, 22))
        self.txt_provedor_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_provedor_contacto.setObjectName("txt_provedor_contacto")
        self.txt_nom_provedor = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txt_nom_provedor.setGeometry(QtCore.QRect(170, 170, 171, 22))
        self.txt_nom_provedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nom_provedor.setObjectName("txt_nom_provedor")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(370, 200, 49, 16))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(410, 150, 49, 16))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.listWidget = QtWidgets.QListWidget(parent=self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(510, 160, 256, 192))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(560, 90, 161, 31))
        self.label_14.setObjectName("label_14")
        self.btn_add_supplier = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_add_supplier.setGeometry(QtCore.QRect(560, 420, 131, 51))
        self.btn_add_supplier.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_supplier.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_add_supplier.setObjectName("btn_add_supplier")
        self.msj_error_provedor = QtWidgets.QLabel(parent=self.tab_2)
        self.msj_error_provedor.setGeometry(QtCore.QRect(50, 530, 461, 31))
        self.msj_error_provedor.setStyleSheet("color: rgb(255, 0, 0);")
        self.msj_error_provedor.setText("")
        self.msj_error_provedor.setObjectName("msj_error_provedor")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(80, 90, 51, 31))
        self.label_15.setObjectName("label_15")
        self.txt_rut = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txt_rut.setGeometry(QtCore.QRect(170, 100, 171, 22))
        self.txt_rut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_rut.setObjectName("txt_rut")
        self.comboBox = QtWidgets.QComboBox(parent=self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(550, 30, 171, 22))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame = QtWidgets.QFrame(parent=self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 90, 431, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.tableView = QtWidgets.QTableView(parent=self.frame)
        self.tableView.setGeometry(QtCore.QRect(60, 80, 281, 251))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(130, 10, 171, 31))
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(70, 50, 49, 16))
        self.label_17.setObjectName("label_17")
        self.btn_serch_supier = QtWidgets.QPushButton(parent=self.frame)
        self.btn_serch_supier.setGeometry(QtCore.QRect(290, 50, 21, 21))
        self.btn_serch_supier.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_serch_supier.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_serch_supier.setText("")
        self.btn_serch_supier.setIcon(icon1)
        self.btn_serch_supier.setObjectName("btn_serch_supier")
        self.txt_serch_supier = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_serch_supier.setGeometry(QtCore.QRect(122, 50, 161, 22))
        self.txt_serch_supier.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_serch_supier.setObjectName("txt_serch_supier")
        self.btn_refresh_supplier = QtWidgets.QPushButton(parent=self.frame)
        self.btn_refresh_supplier.setGeometry(QtCore.QRect(350, 90, 75, 24))
        self.btn_refresh_supplier.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh_supplier.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_refresh_supplier.setIcon(icon)
        self.btn_refresh_supplier.setObjectName("btn_refresh_supplier")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(350, 350, 521, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_suppier_prod = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_suppier_prod.setGeometry(QtCore.QRect(220, 120, 121, 41))
        self.btn_suppier_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_suppier_prod.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_suppier_prod.setObjectName("btn_suppier_prod")
        self.lbl_msj_suppier_selected = QtWidgets.QLabel(parent=self.frame_2)
        self.lbl_msj_suppier_selected.setGeometry(QtCore.QRect(20, 40, 491, 41))
        self.lbl_msj_suppier_selected.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.lbl_msj_suppier_selected.setText("")
        self.lbl_msj_suppier_selected.setObjectName("lbl_msj_suppier_selected")
        self.txt_serch_prod = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txt_serch_prod.setGeometry(QtCore.QRect(552, 130, 161, 22))
        self.txt_serch_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_serch_prod.setObjectName("txt_serch_prod")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(500, 130, 49, 16))
        self.label_16.setObjectName("label_16")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 130, 21, 21))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.btn_refresh_prod = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_refresh_prod.setGeometry(QtCore.QRect(770, 170, 75, 21))
        self.btn_refresh_prod.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh_prod.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_refresh_prod.setIcon(icon)
        self.btn_refresh_prod.setObjectName("btn_refresh_prod")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_21 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(70, 110, 121, 21))
        self.label_21.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(60, 160, 131, 21))
        self.label_22.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(90, 220, 101, 21))
        self.label_23.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_23.setObjectName("label_23")
        self.date_tab3_realiza = QtWidgets.QDateEdit(parent=self.tab_3)
        self.date_tab3_realiza.setGeometry(QtCore.QRect(210, 160, 110, 22))
        self.date_tab3_realiza.setObjectName("date_tab3_realiza")
        self.date_tab3_Entrega = QtWidgets.QDateEdit(parent=self.tab_3)
        self.date_tab3_Entrega.setGeometry(QtCore.QRect(210, 220, 110, 22))
        self.date_tab3_Entrega.setObjectName("date_tab3_Entrega")
        self.label_24 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(140, 270, 51, 21))
        self.label_24.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_24.setObjectName("label_24")
        self.txt_tab3_rut = QtWidgets.QLineEdit(parent=self.tab_3)
        self.txt_tab3_rut.setGeometry(QtCore.QRect(210, 110, 113, 22))
        self.txt_tab3_rut.setObjectName("txt_tab3_rut")
        self.txt_tab3_precio = QtWidgets.QLineEdit(parent=self.tab_3)
        self.txt_tab3_precio.setGeometry(QtCore.QRect(210, 270, 113, 22))
        self.txt_tab3_precio.setObjectName("txt_tab3_precio")
        self.comboBox_tab3_estado = QtWidgets.QComboBox(parent=self.tab_3)
        self.comboBox_tab3_estado.setGeometry(QtCore.QRect(140, 400, 171, 22))
        self.comboBox_tab3_estado.setObjectName("comboBox_tab3_estado")
        self.comboBox_tab3_estado.addItem("")
        self.comboBox_tab3_estado.addItem("")
        self.comboBox_tab3_estado.addItem("")
        self.comboBox_tab3_estado.addItem("")
        self.btn_tab3_ingresar = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_tab3_ingresar.setGeometry(QtCore.QRect(710, 540, 111, 51))
        self.btn_tab3_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_tab3_ingresar.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_tab3_ingresar.setObjectName("btn_tab3_ingresar")
        self.txt_plain_tab3_desc = QtWidgets.QPlainTextEdit(parent=self.tab_3)
        self.txt_plain_tab3_desc.setGeometry(QtCore.QRect(510, 120, 291, 81))
        self.txt_plain_tab3_desc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_plain_tab3_desc.setObjectName("txt_plain_tab3_desc")
        self.label_25 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(560, 90, 171, 21))
        self.label_25.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_25.setObjectName("label_25")
        self.lbl_msj_error_orders = QtWidgets.QLabel(parent=self.tab_3)
        self.lbl_msj_error_orders.setGeometry(QtCore.QRect(40, 510, 521, 31))
        self.lbl_msj_error_orders.setText("")
        self.lbl_msj_error_orders.setObjectName("lbl_msj_error_orders")
        self.list_prod_tab3 = QtWidgets.QListWidget(parent=self.tab_3)
        self.list_prod_tab3.setGeometry(QtCore.QRect(510, 290, 256, 192))
        self.list_prod_tab3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.list_prod_tab3.setObjectName("list_prod_tab3")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(560, 220, 161, 31))
        self.label_20.setObjectName("label_20")
        self.label_27 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(500, 260, 49, 16))
        self.label_27.setObjectName("label_27")
        self.btn_refresh_prod_tab3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_refresh_prod_tab3.setGeometry(QtCore.QRect(770, 300, 75, 21))
        self.btn_refresh_prod_tab3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh_prod_tab3.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_refresh_prod_tab3.setIcon(icon)
        self.btn_refresh_prod_tab3.setObjectName("btn_refresh_prod_tab3")
        self.txt_serch_prod_tab3 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.txt_serch_prod_tab3.setGeometry(QtCore.QRect(552, 260, 161, 22))
        self.txt_serch_prod_tab3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_serch_prod_tab3.setObjectName("txt_serch_prod_tab3")
        self.btn_serch_prod_tab3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_serch_prod_tab3.setGeometry(QtCore.QRect(720, 260, 21, 21))
        self.btn_serch_prod_tab3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_serch_prod_tab3.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_serch_prod_tab3.setText("")
        self.btn_serch_prod_tab3.setIcon(icon1)
        self.btn_serch_prod_tab3.setObjectName("btn_serch_prod_tab3")
        self.txt_tab3_cantidad = QtWidgets.QLineEdit(parent=self.tab_3)
        self.txt_tab3_cantidad.setGeometry(QtCore.QRect(210, 330, 113, 22))
        self.txt_tab3_cantidad.setObjectName("txt_tab3_cantidad")
        self.label_55 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(120, 330, 71, 21))
        self.label_55.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_55.setObjectName("label_55")
        self.comboBox_tab3_change = QtWidgets.QComboBox(parent=self.tab_3)
        self.comboBox_tab3_change.setGeometry(QtCore.QRect(560, 30, 191, 22))
        self.comboBox_tab3_change.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_tab3_change.setObjectName("comboBox_tab3_change")
        self.comboBox_tab3_change.addItem("")
        self.comboBox_tab3_change.addItem("")
        self.comboBox_tab3_change.addItem("")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 871, 541))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.table_tab3_edit_order = QtWidgets.QTableView(parent=self.frame_3)
        self.table_tab3_edit_order.setGeometry(QtCore.QRect(10, 60, 631, 371))
        self.table_tab3_edit_order.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_tab3_edit_order.setObjectName("table_tab3_edit_order")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 251, 31))
        self.label_26.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.label_26.setObjectName("label_26")
        self.btn_tab3_edit_order = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_tab3_edit_order.setGeometry(QtCore.QRect(660, 470, 161, 51))
        self.btn_tab3_edit_order.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_tab3_edit_order.setObjectName("btn_tab3_edit_order")
        self.lbl_error_edit_tab3 = QtWidgets.QLabel(parent=self.frame_3)
        self.lbl_error_edit_tab3.setGeometry(QtCore.QRect(30, 470, 541, 41))
        self.lbl_error_edit_tab3.setText("")
        self.lbl_error_edit_tab3.setObjectName("lbl_error_edit_tab3")
        self.frame_baja_orden_tab3 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_baja_orden_tab3.setGeometry(QtCore.QRect(0, 60, 871, 550))
        self.frame_baja_orden_tab3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_baja_orden_tab3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_baja_orden_tab3.setObjectName("frame_baja_orden_tab3")
        self.btn_tab3_edit_order_3 = QtWidgets.QPushButton(parent=self.frame_baja_orden_tab3)
        self.btn_tab3_edit_order_3.setGeometry(QtCore.QRect(690, 480, 161, 51))
        self.btn_tab3_edit_order_3.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_tab3_edit_order_3.setObjectName("btn_tab3_edit_order_3")
        self.tableView_3 = QtWidgets.QTableView(parent=self.frame_baja_orden_tab3)
        self.tableView_3.setGeometry(QtCore.QRect(10, 20, 851, 261))
        self.tableView_3.setObjectName("tableView_3")
        self.label_30 = QtWidgets.QLabel(parent=self.frame_baja_orden_tab3)
        self.label_30.setGeometry(QtCore.QRect(60, 380, 151, 21))
        self.label_30.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_30.setObjectName("label_30")
        self.txt_id_orden_tab3_2 = QtWidgets.QLineEdit(parent=self.frame_baja_orden_tab3)
        self.txt_id_orden_tab3_2.setGeometry(QtCore.QRect(210, 380, 171, 22))
        self.txt_id_orden_tab3_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_id_orden_tab3_2.setObjectName("txt_id_orden_tab3_2")
        self.label_31 = QtWidgets.QLabel(parent=self.frame_baja_orden_tab3)
        self.label_31.setGeometry(QtCore.QRect(100, 430, 111, 21))
        self.label_31.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_31.setObjectName("label_31")
        self.lbl_error_baja_tab3_2 = QtWidgets.QLabel(parent=self.frame_baja_orden_tab3)
        self.lbl_error_baja_tab3_2.setGeometry(QtCore.QRect(20, 480, 641, 41))
        self.lbl_error_baja_tab3_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_error_baja_tab3_2.setText("")
        self.lbl_error_baja_tab3_2.setObjectName("lbl_error_baja_tab3_2")
        self.date_tab3_pay = QtWidgets.QDateEdit(parent=self.frame_baja_orden_tab3)
        self.date_tab3_pay.setGeometry(QtCore.QRect(210, 430, 171, 22))
        self.date_tab3_pay.setObjectName("date_tab3_pay")
        self.txt_id_prod_tab3 = QtWidgets.QLineEdit(parent=self.frame_baja_orden_tab3)
        self.txt_id_prod_tab3.setGeometry(QtCore.QRect(640, 380, 171, 22))
        self.txt_id_prod_tab3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_id_prod_tab3.setText("")
        self.txt_id_prod_tab3.setObjectName("txt_id_prod_tab3")
        self.label_34 = QtWidgets.QLabel(parent=self.frame_baja_orden_tab3)
        self.label_34.setGeometry(QtCore.QRect(530, 380, 91, 21))
        self.label_34.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.date_sale_tab4 = QtWidgets.QDateTimeEdit(parent=self.tab_4)
        self.date_sale_tab4.setGeometry(QtCore.QRect(190, 140, 194, 22))
        self.date_sale_tab4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.date_sale_tab4.setObjectName("date_sale_tab4")
        self.label_28 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(60, 130, 111, 31))
        self.label_28.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(80, 200, 91, 31))
        self.label_29.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_29.setObjectName("label_29")
        self.txt_amount_tab4 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.txt_amount_tab4.setGeometry(QtCore.QRect(190, 210, 191, 22))
        self.txt_amount_tab4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_amount_tab4.setObjectName("txt_amount_tab4")
        self.label_32 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(580, 90, 151, 31))
        self.label_32.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_32.setObjectName("label_32")
        self.btn_register_sale_tab4 = QtWidgets.QPushButton(parent=self.tab_4)
        self.btn_register_sale_tab4.setGeometry(QtCore.QRect(670, 540, 161, 51))
        self.btn_register_sale_tab4.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_register_sale_tab4.setObjectName("btn_register_sale_tab4")
        self.txt_serch_prod_tab4 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.txt_serch_prod_tab4.setGeometry(QtCore.QRect(572, 130, 161, 22))
        self.txt_serch_prod_tab4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_serch_prod_tab4.setObjectName("txt_serch_prod_tab4")
        self.label_75 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_75.setGeometry(QtCore.QRect(520, 130, 49, 16))
        self.label_75.setObjectName("label_75")
        self.btn_refresh_prod_tab4 = QtWidgets.QPushButton(parent=self.tab_4)
        self.btn_refresh_prod_tab4.setGeometry(QtCore.QRect(770, 170, 75, 21))
        self.btn_refresh_prod_tab4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh_prod_tab4.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_refresh_prod_tab4.setIcon(icon)
        self.btn_refresh_prod_tab4.setObjectName("btn_refresh_prod_tab4")
        self.btn_serch_prod_tab4 = QtWidgets.QPushButton(parent=self.tab_4)
        self.btn_serch_prod_tab4.setGeometry(QtCore.QRect(740, 130, 21, 21))
        self.btn_serch_prod_tab4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_serch_prod_tab4.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_serch_prod_tab4.setText("")
        self.btn_serch_prod_tab4.setIcon(icon1)
        self.btn_serch_prod_tab4.setObjectName("btn_serch_prod_tab4")
        self.lbl_msj_error_tab4 = QtWidgets.QLabel(parent=self.tab_4)
        self.lbl_msj_error_tab4.setGeometry(QtCore.QRect(50, 510, 451, 51))
        self.lbl_msj_error_tab4.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_msj_error_tab4.setObjectName("lbl_msj_error_tab4")
        self.tableView_prod_tab4 = QtWidgets.QTableView(parent=self.tab_4)
        self.tableView_prod_tab4.setGeometry(QtCore.QRect(445, 160, 321, 271))
        self.tableView_prod_tab4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView_prod_tab4.setObjectName("tableView_prod_tab4")
        self.frame_unit_price = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_unit_price.setGeometry(QtCore.QRect(190, 90, 361, 291))
        self.frame_unit_price.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_unit_price.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_unit_price.setObjectName("frame_unit_price")
        self.txt_unite_price = QtWidgets.QLineEdit(parent=self.frame_unit_price)
        self.txt_unite_price.setGeometry(QtCore.QRect(120, 90, 131, 22))
        self.txt_unite_price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_unite_price.setObjectName("txt_unite_price")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_unit_price)
        self.label_35.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.label_35.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.label_35.setObjectName("label_35")
        self.btn_price_unit = QtWidgets.QDialogButtonBox(parent=self.frame_unit_price)
        self.btn_price_unit.setGeometry(QtCore.QRect(100, 240, 156, 24))
        self.btn_price_unit.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btn_price_unit.setObjectName("btn_price_unit")
        self.lbl_error_price_unit = QtWidgets.QLabel(parent=self.frame_unit_price)
        self.lbl_error_price_unit.setGeometry(QtCore.QRect(10, 180, 331, 31))
        self.lbl_error_price_unit.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbl_error_price_unit.setText("")
        self.lbl_error_price_unit.setObjectName("lbl_error_price_unit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame_unit_price)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 301, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.label_36 = QtWidgets.QLabel(parent=self.frame_unit_price)
        self.label_36.setGeometry(QtCore.QRect(120, 10, 111, 16))
        self.label_36.setStyleSheet("font: 700 italic 9pt \"Segoe UI\";")
        self.label_36.setObjectName("label_36")
        self.txt_quantity_tab4_2 = QtWidgets.QLineEdit(parent=self.frame_unit_price)
        self.txt_quantity_tab4_2.setGeometry(QtCore.QRect(120, 130, 131, 22))
        self.txt_quantity_tab4_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_quantity_tab4_2.setText("")
        self.txt_quantity_tab4_2.setObjectName("txt_quantity_tab4_2")
        self.label_37 = QtWidgets.QLabel(parent=self.frame_unit_price)
        self.label_37.setGeometry(QtCore.QRect(30, 120, 51, 31))
        self.label_37.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.label_37.setObjectName("label_37")
        self.frame_tab4_edit_sale = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_tab4_edit_sale.setGeometry(QtCore.QRect(0, 50, 881, 571))
        self.frame_tab4_edit_sale.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tab4_edit_sale.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tab4_edit_sale.setObjectName("frame_tab4_edit_sale")
        self.tableView_edit_sale = QtWidgets.QTableView(parent=self.frame_tab4_edit_sale)
        self.tableView_edit_sale.setGeometry(QtCore.QRect(10, 50, 851, 431))
        self.tableView_edit_sale.setObjectName("tableView_edit_sale")
        self.lbl_error_edit_sale = QtWidgets.QLabel(parent=self.frame_tab4_edit_sale)
        self.lbl_error_edit_sale.setGeometry(QtCore.QRect(30, 540, 581, 31))
        self.lbl_error_edit_sale.setText("")
        self.lbl_error_edit_sale.setObjectName("lbl_error_edit_sale")
        self.btn_edit_sale_tab4 = QtWidgets.QPushButton(parent=self.frame_tab4_edit_sale)
        self.btn_edit_sale_tab4.setGeometry(QtCore.QRect(670, 510, 171, 51))
        self.btn_edit_sale_tab4.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_edit_sale_tab4.setObjectName("btn_edit_sale_tab4")
        self.label_33 = QtWidgets.QLabel(parent=self.frame_tab4_edit_sale)
        self.label_33.setGeometry(QtCore.QRect(260, 10, 301, 31))
        self.label_33.setStyleSheet("font: 700 20pt \"Segoe UI\";")
        self.label_33.setObjectName("label_33")
        self.lbl_error_edit_sale_2 = QtWidgets.QLabel(parent=self.frame_tab4_edit_sale)
        self.lbl_error_edit_sale_2.setGeometry(QtCore.QRect(40, 510, 581, 41))
        self.lbl_error_edit_sale_2.setText("")
        self.lbl_error_edit_sale_2.setObjectName("lbl_error_edit_sale_2")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(670, 10, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(500, 80, 141, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_38 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(320, 20, 251, 31))
        self.label_38.setStyleSheet("font: 700 20pt \"Segoe UI\";")
        self.label_38.setObjectName("label_38")
        self.lbl_error_elim = QtWidgets.QLabel(parent=self.tab_5)
        self.lbl_error_elim.setGeometry(QtCore.QRect(150, 570, 511, 31))
        self.lbl_error_elim.setText("")
        self.lbl_error_elim.setObjectName("lbl_error_elim")
        self.frame_elim_venta = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_elim_venta.setGeometry(QtCore.QRect(290, 180, 341, 251))
        self.frame_elim_venta.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_elim_venta.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_elim_venta.setObjectName("frame_elim_venta")
        self.label_47 = QtWidgets.QLabel(parent=self.frame_elim_venta)
        self.label_47.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_47.setObjectName("label_47")
        self.txt_elim_sale = QtWidgets.QLineEdit(parent=self.frame_elim_venta)
        self.txt_elim_sale.setGeometry(QtCore.QRect(90, 70, 201, 22))
        self.txt_elim_sale.setObjectName("txt_elim_sale")
        self.btn_elim_venta = QtWidgets.QPushButton(parent=self.frame_elim_venta)
        self.btn_elim_venta.setGeometry(QtCore.QRect(210, 200, 101, 31))
        self.btn_elim_venta.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_elim_venta.setObjectName("btn_elim_venta")
        self.label_48 = QtWidgets.QLabel(parent=self.frame_elim_venta)
        self.label_48.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label_48.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(parent=self.frame_elim_venta)
        self.label_49.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_49.setObjectName("label_49")
        self.txt_elim_venta_prod = QtWidgets.QLineEdit(parent=self.frame_elim_venta)
        self.txt_elim_venta_prod.setGeometry(QtCore.QRect(90, 120, 201, 22))
        self.txt_elim_venta_prod.setObjectName("txt_elim_venta_prod")
        self.frame_elim_proveedor = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_elim_proveedor.setGeometry(QtCore.QRect(0, -10, 341, 251))
        self.frame_elim_proveedor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_elim_proveedor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_elim_proveedor.setObjectName("frame_elim_proveedor")
        self.label_42 = QtWidgets.QLabel(parent=self.frame_elim_proveedor)
        self.label_42.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_42.setObjectName("label_42")
        self.txt_elim_proveedor = QtWidgets.QLineEdit(parent=self.frame_elim_proveedor)
        self.txt_elim_proveedor.setGeometry(QtCore.QRect(100, 80, 201, 22))
        self.txt_elim_proveedor.setObjectName("txt_elim_proveedor")
        self.btn_elim_proveedor = QtWidgets.QPushButton(parent=self.frame_elim_proveedor)
        self.btn_elim_proveedor.setGeometry(QtCore.QRect(210, 200, 101, 31))
        self.btn_elim_proveedor.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_elim_proveedor.setObjectName("btn_elim_proveedor")
        self.label_43 = QtWidgets.QLabel(parent=self.frame_elim_proveedor)
        self.label_43.setGeometry(QtCore.QRect(60, 10, 181, 16))
        self.label_43.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label_43.setObjectName("label_43")
        self.label_97 = QtWidgets.QLabel(parent=self.frame_elim_proveedor)
        self.label_97.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_97.setObjectName("label_97")
        self.txt_elim_proveedor_prod = QtWidgets.QLineEdit(parent=self.frame_elim_proveedor)
        self.txt_elim_proveedor_prod.setGeometry(QtCore.QRect(100, 130, 201, 22))
        self.txt_elim_proveedor_prod.setObjectName("txt_elim_proveedor_prod")
        self.frame_elim_prod = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_elim_prod.setGeometry(QtCore.QRect(280, 190, 341, 251))
        self.frame_elim_prod.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_elim_prod.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_elim_prod.setObjectName("frame_elim_prod")
        self.label_40 = QtWidgets.QLabel(parent=self.frame_elim_prod)
        self.label_40.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_40.setObjectName("label_40")
        self.txt_elim_prod = QtWidgets.QLineEdit(parent=self.frame_elim_prod)
        self.txt_elim_prod.setGeometry(QtCore.QRect(100, 80, 201, 22))
        self.txt_elim_prod.setObjectName("txt_elim_prod")
        self.btn_elim_prod = QtWidgets.QPushButton(parent=self.frame_elim_prod)
        self.btn_elim_prod.setGeometry(QtCore.QRect(210, 200, 101, 31))
        self.btn_elim_prod.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_elim_prod.setObjectName("btn_elim_prod")
        self.label_41 = QtWidgets.QLabel(parent=self.frame_elim_prod)
        self.label_41.setGeometry(QtCore.QRect(80, 20, 161, 16))
        self.label_41.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label_41.setObjectName("label_41")
        self.frame_elim_orden = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_elim_orden.setGeometry(QtCore.QRect(10, -10, 341, 251))
        self.frame_elim_orden.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_elim_orden.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_elim_orden.setObjectName("frame_elim_orden")
        self.label_44 = QtWidgets.QLabel(parent=self.frame_elim_orden)
        self.label_44.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_44.setObjectName("label_44")
        self.txt_elim_orden = QtWidgets.QLineEdit(parent=self.frame_elim_orden)
        self.txt_elim_orden.setGeometry(QtCore.QRect(90, 70, 201, 22))
        self.txt_elim_orden.setObjectName("txt_elim_orden")
        self.btn_elim_orden = QtWidgets.QPushButton(parent=self.frame_elim_orden)
        self.btn_elim_orden.setGeometry(QtCore.QRect(210, 200, 101, 31))
        self.btn_elim_orden.setStyleSheet("background-color: rgb(255, 212, 126);")
        self.btn_elim_orden.setObjectName("btn_elim_orden")
        self.label_45 = QtWidgets.QLabel(parent=self.frame_elim_orden)
        self.label_45.setGeometry(QtCore.QRect(20, 10, 231, 16))
        self.label_45.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(parent=self.frame_elim_orden)
        self.label_46.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_46.setObjectName("label_46")
        self.txt_elim_orden_prod = QtWidgets.QLineEdit(parent=self.frame_elim_orden)
        self.txt_elim_orden_prod.setGeometry(QtCore.QRect(90, 120, 201, 22))
        self.txt_elim_orden_prod.setObjectName("txt_elim_orden_prod")
        self.tabWidget.addTab(self.tab_5, "")

        #MARCADOR
        #CAMBIAR CADA VEZ QUE SE COPIE Y PEGUE EL GUI
        """
        self.frame_baja_orden_tab3 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_baja_orden_tab3.setGeometry(QtCore.QRect(0, 60, 871, 550))
        self.frame_baja_orden_tab3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_baja_orden_tab3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_baja_orden_tab3.setObjectName("frame_baja_orden_tab3")
        """


        self.frame.setVisible(False)
        self.frame_2.setVisible(False)
        self.frame_prod1.setVisible(False)
        self.frame_prod2.setVisible(False)
        self.frame_3.setVisible(False)
        self.frame_baja_orden_tab3.setVisible(False)
        self.frame_unit_price.setVisible(False)
        self.frame_tab4_edit_sale.setVisible(False)


        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.btn_agre.clicked.connect(self.btn_add_prod)
        self.btn_add_supplier.clicked.connect(self.add_supplier)
        self.btn_add_supplier.clicked.connect(self.add_supplier_prod)
        self.btn_generate_informe.clicked.connect(self.informe)







        self.comboBox.currentIndexChanged.connect(self.handle_combobox_change)
        self.btn_serch_supier.clicked.connect(self.btn_print_serch_suppier)
        #TABLA DE PROVEDORES
        self.model = QStandardItemModel()
        self.tableView.setModel(self.model)
        self.tableView.setSelectionMode(self.tableView.SelectionMode.SingleSelection)
        self.model.setColumnCount(3)
        self.column_names = ["RUT", "Nombre", "Contacto"]
        self.model.setHorizontalHeaderLabels(self.column_names)
        self.tableView.clicked.connect(self.get_row_selection)
        self.row_data= None
        #TABLA EDITAR PRODUCTOS
        self.model_prod= QStandardItemModel()
        self.tableView_prod.setModel(self.model_prod)
        self.model_prod.setColumnCount(6)
        self.column_names_prod=["Id","nombre","descripcion","categoria","precio","stock"]
        self.model_prod.setHorizontalHeaderLabels(self.column_names_prod)
        self.tableView_prod.setSelectionMode(self.tableView_prod.SelectionMode.SingleSelection)
        self.model_prod.dataChanged.connect(lambda topLeft, model=self.model_prod: self.get_item_change(topLeft, self.model_prod))
        self.prod_cahnge=tuple()
        self.btn_cahnge_prod3.clicked.connect(self.def_btn_change_prod)
        self.btn_refresh_prod_2.clicked.connect(lambda:self.refresh_prods(self.model_prod,self.tableView_prod))
        self.comboBox_prod.currentIndexChanged.connect(self.combobox_prod_change)
        self.btn_suppier_prod.clicked.connect(self.add_prod_suppier2)
        self.btn_serch_nom_prod.clicked.connect(lambda: self.btn_print_serch_prod_tab_products(self.txt_serch_prod_3.text(),self.model_prod,self.tableView_prod,self.lbl_msj_error_3))
        #self.listWidget
        self.listWidget.setSelectionMode(self.listWidget.SelectionMode.MultiSelection)
        self.btn_suppier_prod.clicked.connect(lambda :self.btn_click_refresh_prod(self.listWidget))
        self.pushButton_2.clicked.connect(lambda: self.btn_print_serch_prod_tab_suppier(self.txt_serch_prod.text(),self.listWidget))
        self.btn_refresh_prod.clicked.connect(lambda:self.btn_click_refresh_prod(self.listWidget))
        partial_tab2_changed = partial(self.tab_changed, listWidget=self.listWidget)
        # Conecta la señal currentChanged al método parcial
        self.tabWidget.currentChanged.connect(partial_tab2_changed)

        #TAB 3
        #self.list_prod_tab3
        self.list_prod_tab3.setSelectionMode(self.list_prod_tab3.SelectionMode.NoSelection)
        self.btn_refresh_prod_tab3.clicked.connect(lambda:self.btn_click_refresh_prod(self.list_prod_tab3))
        self.btn_serch_prod_tab3.clicked.connect(lambda: self.btn_print_serch_prod_tab_suppier(self.txt_serch_prod_tab3.text(), self.list_prod_tab3))
        partial_tab3_changed = partial(self.tab_changed, listWidget=self.list_prod_tab3)
        # Conecta la señal currentChanged al método parcial
        self.tabWidget.currentChanged.connect(partial_tab3_changed)
        self.comboBox_tab3_change.currentIndexChanged.connect(self.comboBox_change_tab3)
        #TABLA DE EDITAR ORDENES
        self.model_orders = QStandardItemModel()
        self.table_tab3_edit_order.setModel(self.model_orders)
        self.model_orders.setColumnCount(8)
        self.column_names_orders = ["Id Orden", "Rut", "Fecha Realiza", "Fecha Entrega", "Precio", "Estado","Descripcion","Id Producto","Cantidad"]
        self.model_orders.setHorizontalHeaderLabels(self.column_names_orders)
        self.order_change=None
        self.model_orders.dataChanged.connect(lambda topLeft, model=self.model_orders: self.get_item_change(topLeft, self.model_orders))
        self.btn_tab3_edit_order.clicked.connect(self.btn_click_edit_order_tab3)
        # DAR DE BAJA ORDENES
        self.frame_baja_orden_tab3.setVisible(False)
        self.tableView_3.setModel(self.model_orders)
        #TAB 4
        self.model_prod_ta4 = QStandardItemModel()
        self.tableView_prod_tab4.setModel(self.model_prod_ta4)
        self.model_prod_ta4.setColumnCount(4)
        self.column_names_prod_tab4 = ["Id", "nombre", "stock", "precio"]
        self.model_prod_ta4.setHorizontalHeaderLabels(self.column_names_prod_tab4)
        self.btn_serch_prod_tab4.clicked.connect(lambda: self.btn_print_serch_prod_tab_products(self.txt_serch_prod_tab4.text(),self.model_prod_ta4,self.tableView_prod_tab4,self.lbl_msj_error_tab4))
        self.btn_refresh_prod_tab4.clicked.connect(lambda: self.refresh_prods(self.model_prod_ta4,self.tableView_prod_tab4))

        self.tableView_prod_tab4.selectionModel().selectionChanged.connect(
            lambda selected: MisMetodos.on_selection_changed(selected, self.model_prod_ta4)
        )
        self.btn_refresh_supplier.clicked.connect(self.btn_click_refresh_supplier)
        self.btn_tab3_ingresar.clicked.connect(self.add_order_btn)
        self.txt_tab3_rut.textChanged.connect(self.rut_tab3_detected)
        self.btn_tab3_edit_order_3.clicked.connect(self.btn_click_unsubscribe_tab3)
        self.btn_register_sale_tab4.clicked.connect(self.btn_sale_clicked)
        self.btn_price_unit.accepted.connect(self.process_products)
        self.current_index = 0
        self.comboBox_2.currentIndexChanged.connect(self.change_combobox)
        #TABLA EDIT SALE
        self.sale_change=list
        self.model_sale = QStandardItemModel()
        self.tableView_edit_sale.setModel(self.model_sale)
        self.model_sale.setColumnCount(6)
        self.column_names_orders = ["Id Venta","Fecha Venta","Monto Total","Id Producto","Cantidad","Precio Unitario"]
        self.model_sale.setHorizontalHeaderLabels(self.column_names_orders)
        self.model_sale.dataChanged.connect(
            lambda topLeft, model=self.model_sale: self.get_item_change(topLeft, self.model_sale))
        self.btn_edit_sale_tab4.clicked.connect(self.btn_click_edit_sale_tab4)
        #TAB5
        self.btn_elim_prod.clicked.connect(self.elim_prod_btn)
        self.btn_elim_orden.clicked.connect(self.elim_order)
        self.btn_elim_proveedor.clicked.connect(self.elim_supier)
        self.frame_elim_prod.setVisible(True)
        self.frame_elim_venta.setVisible(False)
        self.frame_elim_orden.setVisible(False)
        self.frame_elim_proveedor.setVisible(False)
        self.comboBox_3.currentIndexChanged.connect(self.change_combobox_elim)




    def btn_add_prod(self):
         # Conectar la función de validación al evento de clic del botón
        nom_pord=self.txt_nom_prod.text()
        cat_prod=self.txt_cat_prod.text()
        stock_prod=self.txt_stock_prod.text()
        des_prod = self.des_prod.toPlainText()
        precio_prod=self.txt_precio_prod.text()
        mensaje = MisMetodos.validar_producto(nom_pord, precio_prod, stock_prod, cat_prod, des_prod)
        if GestionInventario.view_prod_with_name(nom_pord,"SELECT Id, nombre FROM Producto WHERE nombre = %(name)s"):
            self.lbl_msj_error.setText("ya hay un producto con ese nombre ingresado.")
        else:
           self.lbl_msj_error.setText(mensaje)
           if mensaje == "Todos los productos validados correctamente":
            GestionInventario.add_producto(nom_pord,des_prod,cat_prod,precio_prod,stock_prod)

    def tab_changed(self, index,listWidget):
        self.txt_tab3_rut.setText("")
        if index == 1 :
          try:
              listWidget.clear()
              MisMetodos.write_table_prod(listWidget,GestionInventario.show_prod_table())
          except Exception as e:
              print("Error en funcion tab_changed", e)
        if index== 2:
            try:
                listWidget.clear()
                sql_sentence = "SELECT * FROM Producto"
                MisMetodos.write_table_prod(listWidget, GestionInventario.view_table(sql_sentence))
            except Exception as e:
                print("Error en funcion tab_changed", e)
        if index == 3:
            sql_sentence="SELECT Id, nombre,stock,precio FROM inventario.producto WHERE stock > 0"
            self.list_prods = GestionInventario.view_table(sql_sentence)
            self.model.setRowCount(len(self.list_prods))
            self.fill_table(self.list_prods, self.model_prod_ta4)
            self.not_editable_table(self.model_prod_ta4)



    def add_supplier(self):
        rut= self.txt_rut.text()
        nom_supplier = self.txt_nom_provedor.text()
        contacto_supplier = self.txt_provedor_contacto.text()
        termino_pago= self.pl_txt_termino_pago.toPlainText()
        mensaje= MisMetodos.validate_supplier(rut,nom_supplier,contacto_supplier,termino_pago)
        if GestionInventario.view_supier(rut):
            self.msj_error_provedor.setText("Ese provedor ya esta ingresado.")
        else:
            self.msj_error_provedor.setText(mensaje)
            if mensaje == "provedor agregado correctamente":
                GestionInventario.add_supplier_db(rut,nom_supplier,contacto_supplier,termino_pago)





    def add_supplier_prod(self):
        rut= self.txt_rut.text()
        products= MisMetodos.get_prod_link_supplier(self.listWidget.selectedItems())
        mensaje=self.msj_error_provedor.text()
        if mensaje=="provedor agregado correctamente":
            GestionInventario.add_supplier_prod(rut,products)

    def handle_combobox_change(self, index):
        if index == 1:
            self.list_supplier = GestionInventario.show_supplier()
            self.model.setRowCount(len(self.list_supplier))
            self.fill_table(self.list_supplier,self.model)
            self.not_editable_table(self.model)
            self.frame.setVisible(True)  # Mostrar el frame si se selecciona la opción 1
            self.frame_2.setVisible(True)
        else:
            self.frame.setVisible(False)  # Ocultar el frame si se selecciona otra opción
            self.frame_2.setVisible(False)

    def fill_table(self,list_items: list,model):

        for row, list_data in enumerate(list_items):
            for col, data in enumerate(list_data):
                self.set_item(row, col, str(data),model)

    def set_item(self, row, col, data,model):
       item = QStandardItem(data)
       model.setItem(row, col, item)

    def not_editable_table(self,model):
        for row in range(model.rowCount()):
            for column in range(model.columnCount()):
                item = model.item(row, column)
                if item is not None:
                    item.setEditable(False)

    def get_row_selection(self, index):
        fila_seleccionada = index.row()
        datos_fila = []
        for columna in range(self.model.columnCount()):
            item = self.model.item(fila_seleccionada, columna)
            datos_fila.append(item.text())
        tupla_fila = tuple(datos_fila)
        self.lbl_msj_suppier_selected.setText(f"Se asignaran los productos seleccionados a el provedor:{tupla_fila[0]}")
        self.row_data= tupla_fila

    def btn_print_serch_prod_tab_suppier(self,nom_prod:str,listWidget):

        sql_sentence="SELECT Id, nombre FROM Producto WHERE nombre = %(name)s"
        prod_find=GestionInventario.view_prod_with_name(nom_prod,sql_sentence)
        try:
            if nom_prod =="":
                self.msj_error_provedor.setText("Ingrese un producto para su busqeda.")
            else:
             if prod_find:
                listWidget.clear()
                MisMetodos.write_table_prod(listWidget, prod_find)
             else:
                 self.msj_error_provedor.setText("Producto no encontrado.")
        except Exception as e:
            print("Error en funcion tab_changed", e)

    def btn_print_serch_prod_tab_products(self, nom_prod: str,model,table,msj):

        sql_sentence = "SELECT * FROM Producto WHERE nombre = %(name)s"
        prod_find = GestionInventario.view_prod_with_name(nom_prod, sql_sentence)
        try:
            if nom_prod == "":
                    msj.setText("Ingrese un producto para su busqeda.")
            else:
                if prod_find:
                    model.removeRows(0, model.rowCount())
                    table.viewport().update()
                    self.fill_table(prod_find,model)
                else:
                    msj.setText("Producto no encontrado.")
        except Exception as e:
            print("Error en funcion tab_changed", e)


    def refresh_prods(self,model,table):
        if model == self.model_prod:
            sql_sentence = "SELECT * FROM Producto"
        else:
            sql_sentence="SELECT Id, nombre,stock,precio FROM inventario.producto WHERE stock > 0"
        list_prods= GestionInventario.view_table(sql_sentence)
        model.removeRows(0, model.rowCount())
        table.viewport().update()
        self.fill_table(list_prods,model)



    def btn_print_serch_suppier(self):
        rut_suppier= self.txt_serch_supier.text()
        self.list_serch_supplier = GestionInventario.view_supier(rut_suppier)
        try:
            if rut_suppier=="":
                self.msj_error_provedor.setText("Ingrese un provedor para su busqeda.")
            else:
                if self.list_serch_supplier:
                    self.model.removeRows(0, self.model.rowCount())
                    self.fill_table(self.list_serch_supplier)
                    self.not_editable_table(self.model)
                else:
                    self.msj_error_provedor.setText("provedor no encontrado")
        except Exception as e:
            print("Error en funcion btn_print_serch_suppier:", e)

    def btn_click_refresh_prod(self,listWidget):
       try:
        listWidget.clear()
        if listWidget==self.listWidget:
         MisMetodos.write_table_prod(listWidget, GestionInventario.show_prod_table())
        if listWidget== self.list_prod_tab3:
            sql_sentence = "SELECT * FROM Producto"
            MisMetodos.write_table_prod(listWidget, GestionInventario.view_table(sql_sentence))
       except Exception as e:
           print("ha ocurrido un error al refrescar: ", e)

    def btn_click_refresh_supplier(self):
        try:
            self.list_supplier = GestionInventario.show_supplier()
            self.model.setRowCount(len(self.list_supplier))
            self.fill_table(self.list_supplier)
            self.not_editable_table(self.model)
        except Exception as e:
            print("Ha ocurrido un error al refrescar:", e)

    def add_prod_suppier2(self):
        list_products=MisMetodos.get_prod_link_supplier(self.listWidget.selectedItems())
        if not list_products:
            self.msj_error_provedor.setText("Seleccione un producto")
        elif self.row_data==None:
            self.msj_error_provedor.setText("Seleccione un proveedro")
        else:
            self.row_data=self.row_data[0]
            GestionInventario.add_supplier_prod(self.row_data,list_products)

    def combobox_prod_change(self,index):
        if index == 0:
            self.frame_prod1.setVisible(False)
            self.frame_prod2.setVisible(False)
        else:
            self.frame_prod1.setVisible(True)
            self.frame_prod2.setVisible(True)
            sql_sentence = "SELECT * FROM Producto"
            self.list_prods= GestionInventario.view_table(sql_sentence)
            self.model.setRowCount(len(self.list_prods))
            self.fill_table(self.list_prods,self.model_prod)

    def get_item_change(self, topLeft: QModelIndex,model):
        # Obtener las coordenadas de la celda que ha cambiado
        row = topLeft.row()
        column = topLeft.column()
        self.column_header = model.headerData(column, Qt.Orientation.Horizontal)
        id = model.index(row, 0)
        first_cell_attribute = model.data(id)
        new_value = model.data(topLeft)
        if model == self.model_prod:
            self.prod_cahnge=(first_cell_attribute,self.column_header,new_value)
        if model == self.model_orders:
            if self.column_header =="Fecha Realiza":
                colum_date_delivery=column+1
                index = self.model_orders.index(row, colum_date_delivery)
                self.date_delivery = self.model_orders.data(index)
            elif self.column_header =="Fecha Entrega":
                colum_date_initial=column-1
                index = self.model_orders.index(row, colum_date_initial)
                self.colum_date_initial = self.model_orders.data(index)
            elif self.column_header == "Cantidad":
                column_id_prod=column-1
                index = self.model_orders.index(row, column_id_prod)
                self.column_id_prod = self.model_orders.data(index)
            self.order_change=(first_cell_attribute,self.column_header,new_value)
        if model==self.model_sale:
            id_prod = model.index(row, 3)
            id_prod_sale= model.data(id_prod)
            self.sale_change_list=(first_cell_attribute,id_prod_sale,self.column_header,new_value)
            self.sale_change=list(self.sale_change_list)




    def def_btn_change_prod(self):

        msj_error=MisMetodos.validate_one_data_prod(self.prod_cahnge[2],self.prod_cahnge[1])
        self.lbl_msj_error_3.setText(msj_error)
        if msj_error =="Atributo validado correctamente":
          GestionInventario.update_pord(self.prod_cahnge)

    def add_order_btn(self):
       try:
        rut=self.txt_tab3_rut.text()
        date_initial=self.date_tab3_realiza.date().toPyDate()
        date_delivery=self.date_tab3_Entrega.date().toPyDate()
        price=self.txt_tab3_precio.text()
        state = self.comboBox_tab3_estado.currentText()
        cantidad= self.txt_tab3_cantidad.text()
        description=self.txt_plain_tab3_desc.toPlainText()
        list_products=MisMetodos.get_prod_link_supplier(self.list_prod_tab3.selectedItems())
        msj_error= MisMetodos.validate_orders(rut, date_initial, date_delivery, price, state,cantidad,description,list_products)
        self.lbl_msj_error_orders.setText(msj_error)
       except Exception as e:
           print(e)

    def rut_tab3_detected(self):
        rut=self.txt_tab3_rut.text()
        if rut=="" or not GestionInventario.view_supier(rut):
            self.lbl_msj_error_orders.setText("El rut ingresado no existe")
        else:
            self.list_prod_tab3.setSelectionMode(self.list_prod_tab3.SelectionMode.ExtendedSelection)
            self.lbl_msj_error_orders.setText("")
            self.list_prod_tab3.clear()
            MisMetodos.write_table_prod(self.list_prod_tab3, GestionInventario.view_suppier_prod(rut))

    def comboBox_change_tab3(self,index):
        if index==0:
            self.frame_baja_orden_tab3.setVisible(False)
            self.frame_3.setVisible(False)
        elif index==1:
            self.frame_baja_orden_tab3.setVisible(False)
            self.frame_3.setVisible(True)
            list_order=GestionInventario.elements_edit_order()
            self.fill_table(list_order,self.model_orders)
            self.not_editable_table(self.model_orders)
        else:
            self.frame_3.setVisible(False)
            self.frame_baja_orden_tab3.setVisible(True)
            list_order = GestionInventario.elements_edit_order()
            self.fill_table(list_order, self.model_orders)
            self.not_editable_table(self.model_orders)


    def not_editable_table(self,model):
        for row in range(model.rowCount()):
            for column in range(model.columnCount()):
                item = model.item(row, column)
                if model == self.model_orders:
                    if column == 0 or column ==1 or column==7:
                        item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)
                if model== self.model_sale:
                    if column==0 or column==3:
                        item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)

    def btn_click_edit_order_tab3(self):
        try:
            if self.column_header =="Fecha Realiza":
                msj_error =MisMetodos.validate_update_order(self.order_change[1],self.order_change[2],self.order_change[0],self.date_delivery)
                self.lbl_error_edit_tab3.setText(msj_error)
            elif self.column_header=="Fecha Entrega":
                msj_error=MisMetodos.validate_update_order(self.order_change[1], self.order_change[2], self.order_change[0],self.colum_date_initial)
                self.lbl_error_edit_tab3.setText(msj_error)
            elif self.column_header == "Cantidad":
                msj_error = MisMetodos.validate_update_order(self.order_change[1], self.order_change[2],self.order_change[0], self.column_id_prod)
                self.lbl_error_edit_tab3.setText(msj_error)
            else:
                msj_error=MisMetodos.validate_update_order(self.order_change[1], self.order_change[2], self.order_change[0])
                self.lbl_error_edit_tab3.setText(msj_error)
        except Exception as e:
            print(e)

    def btn_click_unsubscribe_tab3(self):
        id_prod=self.txt_id_prod_tab3.text()
        id_order=self.txt_id_orden_tab3_2.text()
        payment_date=self.date_tab3_pay.date().toPyDate()
        msj_error=MisMetodos.validate_order_baja(id_order,payment_date)
        self.lbl_error_baja_tab3_2.setText(msj_error)
        if msj_error=="dado de baja correctamente":
                self.unsubscribe_rows_orders(id_order,id_prod)


    def unsubscribe_rows_orders(self,id_order,id_prod):
        rows_to_delete = []
        for row in range(self.model_orders.rowCount()):
            id_item = self.model_orders.item(row, 0)
            #other_item = self.model_orders.item(row, 7)
            if id_item is not None and id_item.text() == id_order:
                rows_to_delete.append(row)  # Guardamos el índice de fila

        for row in reversed(rows_to_delete):
            #id_item = self.model_orders.item(row, 0)  # Assuming ID is in the first column
            other_item = self.model_orders.item(row, 7)  # Assuming other item is in the eighth column
            if id_prod == "":
                self.model_orders.removeRow(row)  # Si el ID de producto está vacío, eliminamos la fila
            elif other_item is not None and other_item.text() == id_prod:
                self.model_orders.removeRow(row)  # Si el ID de producto coincide, eliminamos la fila
    def btn_sale_clicked(self):
        sale_date = self.date_sale_tab4.dateTime().toPyDateTime()
        total_amount=self.txt_amount_tab4.text()
        self.list_prods = MisMetodos.list_prods_tab4
        try:
            msj_error= MisMetodos.validate_sales_record(sale_date, total_amount)
            self.lbl_msj_error_tab4.setText(msj_error)
            if not self.list_prods:
                self.lbl_msj_error_tab4.setText("Seleccione al menos un producto")
            elif msj_error=="Venta agregada exitosamente.":
               self.frame_unit_price.setVisible(True)
               first_product = self.list_prods[0]
               self.textBrowser.setText(f"Ingrese el precio por c/u del producto: {first_product[0]} \nnombre del producto: {first_product[1]}")
        except Exception as e:
                print("error en btn_sale_clicked",e)

    def process_products(self):
      try:
         self.last_id_sale = MisMetodos.last_id_sale
         self.unit_priece = self.txt_unite_price.text()
         self.quantity = self.txt_quantity_tab4_2.text()
         first_product = self.list_prods[0]
         msj_error = MisMetodos.validate_unit_priece(self.last_id_sale, first_product[0], self.quantity, self.unit_priece)
         self.lbl_error_price_unit.setText(msj_error)
         if msj_error=="Agregado correctamente":
            self.txt_unite_price.setText("")
            self.txt_quantity_tab4_2.setText("")
            if self.list_prods:
                next_product = self.list_prods[0]
                self.textBrowser.setText(f"Ingrese el precio por c/u del producto: {next_product[0]} \nnombre del producto: {next_product[1]}")
            else:
                self.frame_unit_price.setVisible(False)
      except Exception as e:
             print(e)
    def change_combobox(self,index):
        if index==0:
            self.frame_tab4_edit_sale.setVisible(False)
        else:
            self.frame_tab4_edit_sale.setVisible(True)
            sql_sentence = (
                "SELECT "
                "v.id AS VentaId, "
                "v.fecha_venta, v.monto_total, "
                "vp.ProductoId, vp.cantidad, "
                "vp.precio_unitario "
                "FROM "
                "Ventas v "
                "JOIN "
                "VentaProducto vp ON v.id = vp.VentaId;"
            )
            self.list_sales = GestionInventario.view_table(sql_sentence)
            self.model.setRowCount(len(self.list_sales))
            self.fill_table(self.list_sales, self.model_sale)
            self.not_editable_table(self.model_sale)

    def btn_click_edit_sale_tab4(self):
        try:
            print(self.sale_change)
            print(type(self.sale_change))
            msj_error=MisMetodos.validate_change_sale(self.sale_change)
            self.lbl_error_edit_sale.setText(msj_error)
        except Exception as e:
            print(e)

    def elim_prod_btn(self):
        id_prod=self.txt_elim_prod.text()
        msj_error=GestionInventario.elim_prod(id_prod)
        self.lbl_error_elim.setText(msj_error)

    def elim_order(self):
        id_order=self.txt_elim_orden.text()
        id_prod=self.txt_elim_orden_prod.text()
        print(id_order)
        print(id_prod)
        if id_prod=="":
            print("entro en el if")
            GestionInventario.elim_order_prod(id_order,id_prod)
            msj_error=GestionInventario.elim_order(id_order)
            self.lbl_error_elim.setText(msj_error)
        else:
            print("entro en else")
            msj_error=GestionInventario.elim_order_prod(id_order,id_prod)
            self.lbl_error_elim.setText(msj_error)

    def elim_supier(self):
        id_suppier=self.txt_elim_proveedor.text()
        id_prod=self.txt_elim_proveedor_prod.text()
        if id_prod=="":
            GestionInventario.elim_supier_prod(id_suppier,id_prod)
            msj_errr=GestionInventario.elim_suppier(id_suppier)
            self.lbl_error_elim.setText(msj_errr)
        else:
            msj_error=GestionInventario.elim_supier_prod(id_suppier, id_prod)
            self.lbl_error_elim.setText(msj_error)

    def change_combobox_elim(self,index):
        if index==0:
            self.frame_elim_prod.setVisible(True)
            self.frame_elim_venta.setVisible(False)
            self.frame_elim_orden.setVisible(False)
            self.frame_elim_proveedor.setVisible(False)
        elif index==1:
            self.frame_elim_prod.setVisible(False)
            self.frame_elim_venta.setVisible(False)
            self.frame_elim_orden.setVisible(False)
            self.frame_elim_proveedor.setVisible(True)
        elif index==2:
            self.frame_elim_prod.setVisible(False)
            self.frame_elim_venta.setVisible(False)
            self.frame_elim_orden.setVisible(True)
            self.frame_elim_proveedor.setVisible(False)
        elif index==3:
            self.frame_elim_prod.setVisible(False)
            self.frame_elim_venta.setVisible(True)
            self.frame_elim_orden.setVisible(False)
            self.frame_elim_proveedor.setVisible(False)


    #def elim_sale_btn(self):
       # id_sale=self.txt_eli


    def informe(self):
       try:
        sql_sentence="SELECT * FROM inventario.producto"
        data=GestionInventario.view_table(sql_sentence)
        nom_arch="resultado.xlsx"
        MisMetodos.escribir_excel(data,nom_arch)
        self.lbl_msj_error.setText("Generado correctamente")
       except Exception as e:
           print(e)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Productos"))
        self.label_2.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">Nombre:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">Categoria:</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">Stock:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">Descripcion:</span></p><p><span style=\" font-size:14pt;\"><br/></span></p></body></html>"))
        self.btn_agre.setText(_translate("Dialog", "Agregar"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Agregar Producto</span></p></body></html>"))
        self.lbl_msj_error.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">precio:</span></p></body></html>"))
        self.comboBox_prod.setItemText(0, _translate("Dialog", "Agregar Producto"))
        self.comboBox_prod.setItemText(1, _translate("Dialog", "Editar productos"))
        self.btn_cahnge_prod3.setText(_translate("Dialog", "Aplicar"))
        self.btn_refresh_prod_2.setText(_translate("Dialog", "refresh"))
        self.txt_serch_prod_3.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre</p></body></html>"))
        self.txt_serch_prod_3.setPlaceholderText(_translate("Dialog", "Ingrese el nombre..."))
        self.label_39.setText(_translate("Dialog", "Buscar:"))
        self.lbl_msj_error_3.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_generate_informe.setText(_translate("Dialog", "Generar Informe de Stock"))
        self.label_19.setText(
            _translate("Dialog", "<html><head/><body><p align=\"center\">Editar prodcutos</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Productos"))
        self.label_7.setText(_translate("Dialog",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">Gestion de provedores</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:14pt;\">Nombre:</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:14pt;\">Contacto:</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:14pt;\">Termino de Pago:</span></p></body></html>"))
        self.pl_txt_termino_pago.setToolTip(_translate("Dialog",
                                                       "<html><head/><body><p>condiciones acordadas entre un proveedor y un cliente para realizar el pago de bienes o servicios. Generalemnte, especifica cuándo y cómo se espera que se realice el pago.</p></body></html>"))
        self.txt_provedor_contacto.setToolTip(_translate("Dialog",
                                                         "<html><head/><body><p>Ingrese el medio o medios de contacto con la empresa</p></body></html>"))
        self.txt_nom_provedor.setToolTip(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre de la empresa provedora.</p></body></html>"))
        self.listWidget.setToolTip(_translate("Dialog",
                                              "<html><head/><body><p>Seleccione los porductos que este provedor le va a suministrar</p></body></html>"))
        self.label_14.setText(_translate("Dialog",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Lista de Productos</span></p></body></html>"))
        self.btn_add_supplier.setText(_translate("Dialog", "Ingresar"))
        self.label_15.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:14pt;\">RUT:</span></p></body></html>"))
        self.txt_rut.setToolTip(
            _translate("Dialog", "<html><head/><body><p>Ingrese el rut de la empresa XX.XXX.XXX-X</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "Agregar Nuevo Proveedor"))
        self.comboBox.setItemText(1, _translate("Dialog", "Agregar Nuevos productos"))
        self.label_18.setText(_translate("Dialog",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Lista de Provedores</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog",
                                         "<html><head/><body><p align=\"center\">Buscar:</p><p align=\"center\"><br/></p></body></html>"))
        self.txt_serch_supier.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.txt_serch_supier.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre</p></body></html>"))
        self.txt_serch_supier.setPlaceholderText(_translate("Dialog", "Ingrese el rut..."))
        self.btn_refresh_supplier.setText(_translate("Dialog", "refresh"))
        self.btn_suppier_prod.setText(_translate("Dialog", "Agregar"))
        self.txt_serch_prod.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre</p></body></html>"))
        self.txt_serch_prod.setPlaceholderText(_translate("Dialog", "Ingrese el nombre..."))
        self.label_16.setText(_translate("Dialog", "Buscar:"))
        self.btn_refresh_prod.setText(_translate("Dialog", "refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Provedores"))
        self.label_21.setText(_translate("Dialog", "Rut del provedor:"))
        self.label_22.setText(_translate("Dialog", " Fecha Realizacion:"))
        self.label_23.setText(_translate("Dialog", "Fecha Entrega:"))
        self.date_tab3_realiza.setToolTip(_translate("Dialog",
                                                     "<html><head/><body><p>Ingrese la fehca en la que se realizo el pedido al prveedor.</p><p><br/></p></body></html>"))
        self.date_tab3_Entrega.setToolTip(_translate("Dialog",
                                                     "<html><head/><body><p>Ingrese la fecha en que el proveedor entrega el producto.</p></body></html>"))
        self.label_24.setText(_translate("Dialog", "Precio:"))
        self.txt_tab3_rut.setToolTip(_translate("Dialog",
                                                "<html><head/><body><p>debe ingresar el proveedor que le ha echo el pedido.</p></body></html>"))
        self.txt_tab3_precio.setToolTip(
            _translate("Dialog", "<html><head/><body><p>Ingrese el precio del pedido.</p><p><br/></p></body></html>"))
        self.comboBox_tab3_estado.setItemText(0, _translate("Dialog", "Estado"))
        self.comboBox_tab3_estado.setItemText(1, _translate("Dialog", "Entregado"))
        self.comboBox_tab3_estado.setItemText(2, _translate("Dialog", "Pendiente"))
        self.comboBox_tab3_estado.setItemText(3, _translate("Dialog", "Cancelado"))
        self.btn_tab3_ingresar.setText(_translate("Dialog", "Ingresar"))
        self.txt_plain_tab3_desc.setToolTip(_translate("Dialog",
                                                       "<html><head/><body><p>Agrege una descripcion del pedido de ser necesario.</p></body></html>"))
        self.label_25.setText(_translate("Dialog", "Descripcion del pedido:"))
        self.list_prod_tab3.setToolTip(_translate("Dialog",
                                                  "<html><head/><body><p>Seleccione los porductos que este provedor le va a suministrar</p></body></html>"))
        self.label_20.setText(_translate("Dialog",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Lista de Productos</span></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "Buscar:"))
        self.btn_refresh_prod_tab3.setText(_translate("Dialog", "refresh"))
        self.txt_serch_prod_tab3.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre</p></body></html>"))
        self.txt_serch_prod_tab3.setPlaceholderText(_translate("Dialog", "Ingrese el nombre..."))
        self.txt_tab3_cantidad.setToolTip(
            _translate("Dialog", "<html><head/><body><p>Ingrese el precio del pedido.</p><p><br/></p></body></html>"))
        self.label_55.setText(_translate("Dialog", "Cantidad:"))
        self.comboBox_tab3_change.setItemText(0, _translate("Dialog", "Agregar Orden de Compra"))
        self.comboBox_tab3_change.setItemText(1, _translate("Dialog", "Editar Orden de Compra"))
        self.comboBox_tab3_change.setItemText(2, _translate("Dialog", "Dar de baja una orden"))
        self.label_26.setText(
            _translate("Dialog", "<html><head/><body><p align=\"center\">Editar Orden de Compra:</p></body></html>"))
        self.btn_tab3_edit_order.setText(_translate("Dialog", "Ingresar"))
        self.btn_tab3_edit_order_3.setText(_translate("Dialog", "Baja"))
        self.label_30.setText(_translate("Dialog", "Id Orden de Compra:"))
        self.label_31.setText(_translate("Dialog", "Fecha del Pago:"))
        self.txt_id_prod_tab3.setToolTip(_translate("Dialog",
                                                    "<html><head/><body><p>Ingrese el id del producto de una orden si desea eliminar ese producto de la orden especificada</p></body></html>"))
        self.txt_id_prod_tab3.setPlaceholderText(_translate("Dialog", "Opcional..."))
        self.label_34.setToolTip(_translate("Dialog",
                                            "<html><head/><body><p>Ingrese el id del producto de una orden si desea eliminar ese producto de la orden especificada</p></body></html>"))
        self.label_34.setText(_translate("Dialog", "Id Producto:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Gestion de Pedidos"))
        self.label_28.setText(_translate("Dialog", "Fecha de venta:"))
        self.label_29.setText(_translate("Dialog", "Monto Total:"))
        self.label_32.setText(_translate("Dialog", "Lista de Productos"))
        self.btn_register_sale_tab4.setText(_translate("Dialog", "Registrar"))
        self.txt_serch_prod_tab4.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p>Ingrese el nombre</p></body></html>"))
        self.txt_serch_prod_tab4.setPlaceholderText(_translate("Dialog", "Ingrese el nombre..."))
        self.label_75.setText(_translate("Dialog", "Buscar:"))
        self.btn_refresh_prod_tab4.setText(_translate("Dialog", "refresh"))
        self.lbl_msj_error_tab4.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_35.setText(_translate("Dialog", "Precio por Unidad:"))
        self.textBrowser.setHtml(_translate("Dialog",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_36.setText(_translate("Dialog", "Precio por Unidad"))
        self.label_37.setText(_translate("Dialog", "Cantidad:"))
        self.btn_edit_sale_tab4.setText(_translate("Dialog", "Aplicar"))
        self.label_33.setText(
            _translate("Dialog", "<html><head/><body><p align=\"center\">Tabla de Ventas</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Agregar Venta"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Editar Venta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Registrar Venta"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Eliminar Producto"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Eliminar Proveedor"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Eliminar Pedidos"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "Eliminar Ventas"))
        self.label_38.setText(_translate("Dialog",
                                         "<html><head/><body><p align=\"center\">Eliminaciones</p><p align=\"center\"><br/></p></body></html>"))
        self.label_47.setText(_translate("Dialog", "Id Venta"))
        self.btn_elim_venta.setText(_translate("Dialog", "Aplicar"))
        self.label_48.setText(_translate("Dialog", "Eliminar Venta"))
        self.label_49.setText(_translate("Dialog", "Id Producto"))
        self.label_42.setText(_translate("Dialog", "Id Proveedor"))
        self.btn_elim_proveedor.setText(_translate("Dialog", "Aplicar"))
        self.label_43.setText(_translate("Dialog", "Eliminar Proveedor"))
        self.label_97.setText(_translate("Dialog", "Id Producto"))
        self.label_40.setText(_translate("Dialog", "Id producto"))
        self.btn_elim_prod.setText(_translate("Dialog", "Aplicar"))
        self.label_41.setText(_translate("Dialog", "Eliminar Producto"))
        self.label_44.setText(_translate("Dialog", "Id Orden "))
        self.btn_elim_orden.setText(_translate("Dialog", "Aplicar"))
        self.label_45.setText(_translate("Dialog", "Eliminar Orden de compra"))
        self.label_46.setText(_translate("Dialog", "Id Producto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
